# Generated by Django 5.0.4 on 2024-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Whitepaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Վերնագիր"),
                ),
                ("content", models.TextField(verbose_name="Կոնտենտ")),
                (
                    "file",
                    models.FileField(
                        upload_to="Whitepaper", verbose_name="Ֆայլ"
                    ),
                ),
            ],
        ),
    ]
