# Generated by Django 3.1.7 on 2021-04-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_0724'),
        ('main', '0002_auto_20210404_1245'),
    ]

    operations = [
    ]
